# Generated by Django 3.2 on 2021-12-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='班级的名称')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.department', verbose_name='班级所属学院')),
            ],
            options={
                'db_table': 'class',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='学生姓名')),
                ('idcardnumber', models.CharField(max_length=20, unique=True, verbose_name='身份证号')),
                ('sex', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('family_phone', models.CharField(max_length=11, verbose_name='家长手机号')),
                ('anewconunt', models.IntegerField(null=True, verbose_name='重修次数')),
                ('score', models.IntegerField(null=True, verbose_name='综合积分')),
                ('relations', models.CharField(max_length=30, verbose_name='亲子关系')),
                ('address', models.CharField(max_length=100, verbose_name='学生地址')),
                ('dormnumber', models.IntegerField(verbose_name='宿舍号')),
                ('bednumber', models.IntegerField(verbose_name='床号')),
                ('market', models.CharField(max_length=30, verbose_name='市场部')),
                ('cls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cls', to='students.class_a')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
