# Generated by Django 3.2 on 2021-12-14 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('course', '0001_initial'),
        ('register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rollcall',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.department'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='college_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.collegestage', verbose_name='阶段的id'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='course_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.courseplan'),
        ),
        migrations.AddField(
            model_name='rollcall',
            name='teaching_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.teachingtime', verbose_name='教学周期'),
        ),
        migrations.AddField(
            model_name='courses',
            name='college_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.collegestage'),
        ),
        migrations.AddField(
            model_name='courses',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.department'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='classid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class_a'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='counsellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fdy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.courses'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='js', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='room_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jsh', to='course.classroom'),
        ),
        migrations.AddField(
            model_name='courseplan',
            name='teaching_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.teachingtime'),
        ),
        migrations.AddField(
            model_name='collegestage',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.department'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.department'),
        ),
        migrations.AddField(
            model_name='adjustclasstime',
            name='change_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjustclasstime',
            name='course_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseplan'),
        ),
        migrations.AddField(
            model_name='adjustclasstime',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjustclassmap',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.adjustclasstime'),
        ),
    ]
