# Generated by Django 3.2 on 2021-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentScore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='avatar',
            field=models.FileField(default='static/ScoreMarksImg/1.jpg', null=True, upload_to='static/ScoreMarksImg', verbose_name='违纪图片'),
        ),
    ]
