# Generated by Django 3.2 on 2021-12-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentScore', '0003_alter_studentscore_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='avatar',
            field=models.CharField(max_length=300, null=True, verbose_name='违纪图片'),
        ),
    ]
