# Generated by Django 3.2 on 2021-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schoolroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='姓名')),
                ('sex', models.BooleanField(verbose_name='性别')),
                ('birth', models.DateTimeField(verbose_name='出生日期')),
                ('nation', models.CharField(max_length=60, verbose_name='民族')),
                ('address', models.CharField(max_length=60, verbose_name='地址')),
                ('card', models.CharField(max_length=11, verbose_name='身份证号')),
                ('Authority', models.CharField(max_length=11, verbose_name='发证机关')),
                ('ValidDate', models.CharField(max_length=11, verbose_name='证件有效期')),
            ],
            options={
                'db_table': 'school_roll',
                'ordering': ('-id',),
            },
        ),
    ]
