# Generated by Django 3.2 on 2021-12-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolroll',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='schoolroll',
            old_name='birth',
            new_name='Birth',
        ),
        migrations.RenameField(
            model_name='schoolroll',
            old_name='card',
            new_name='IdNum',
        ),
        migrations.RenameField(
            model_name='schoolroll',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='schoolroll',
            old_name='nation',
            new_name='Nation',
        ),
        migrations.RenameField(
            model_name='schoolroll',
            old_name='sex',
            new_name='Sex',
        ),
    ]
