# Generated by Django 3.2 on 2021-12-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolroll', '0003_alter_schoolroll_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolroll',
            name='Authority',
            field=models.CharField(max_length=100, verbose_name='发证机关'),
        ),
        migrations.AlterField(
            model_name='schoolroll',
            name='IdNum',
            field=models.CharField(max_length=100, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='schoolroll',
            name='ValidDate',
            field=models.CharField(max_length=100, verbose_name='证件有效期'),
        ),
    ]
